// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Street   *string `json:"street"`
	City     *string `json:"city"`
	Province *string `json:"province"`
	Zipcode  *int    `json:"zipcode"`
}
